function LB=LowerBound(qU,InvKmm,xbatch,ybatch,z,Beta,Sigmaf,qHyper,Batch,nz,D)
    [EKmb,EKmbbm,Edist]=Expectation(qHyper,xbatch,z,Sigmaf,Batch,nz,D);
    LB=-Batch/2*log(2*pi)+Batch/2*log(Beta)-Beta/2*(ybatch'*ybatch-2*qU.mean'*InvKmm*EKmb*ybatch+qU.mean'*InvKmm*EKmbbm*InvKmm*qU.mean)-...
       Beta/2*trace(qU.covariance*InvKmm*EKmbbm*InvKmm)-Batch*Beta*Sigmaf^2/2+Beta/2*trace(InvKmm*EKmbbm)+...
       -1/2*qU.mean'*InvKmm*qU.mean-1/2*trace(qU.covariance*InvKmm)+1/2*log(det(qU.covariance))+nz/2-...
       1/2*qHyper.mean'*qHyper.mean-1/2*trace(qHyper.covariance)+1/2*log(det(qHyper.covariance))+D/2; 
end